version: '2'
services:
  web:
    build: .
    command: npm run dev
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    environment:
      PORT: 8080
    ports:
      - 8080:8080
  
  mongodb:
    image: mongo
    ports:
        - "27017:27017"
    environment: 
        - MONGO_DATA_DIR=/data/db
    volumes: 
    - ./data/db:/data/db
    command: mongod --smallfiles
  
